# summary: connector/apis/update-connector-last-sync-api.asciidoc:115
# method_request: PUT _connector/my-connector/_last_sync
# description: ''
# type: request
value:
  "{\n    \"last_access_control_sync_error\": \"Houston, we have a problem!\"\
  ,\n    \"last_access_control_sync_scheduled_at\": \"2023-11-09T15:13:08.231Z\",\n\
  \    \"last_access_control_sync_status\": \"pending\",\n    \"last_deleted_document_count\"\
  : 42,\n    \"last_incremental_sync_scheduled_at\": \"2023-11-09T15:13:08.231Z\"\
  ,\n    \"last_indexed_document_count\": 42,\n    \"last_sync_error\": \"Houston,\
  \ we have a problem!\",\n    \"last_sync_scheduled_at\": \"2024-11-09T15:13:08.231Z\"\
  ,\n    \"last_sync_status\": \"completed\",\n    \"last_synced\": \"2024-11-09T15:13:08.231Z\"\
  \n}"
